name: "AP Intercom Agent"
slug: ap_intercom_agent
description: "SIP agent for intercom control."
version: "0.2.0"
arch:
  - aarch64
url: "https://github.com/ikob/AP_intercom_agent"
startup: services
boot: auto
host_network: true
init: false
map:
  - type: media
    read_only: false

options:
  username: "cellphone0"
  password: null
  proxy: null
  register_uri: null
  message_uri: null
  entrance_uri: null
  allowed_callers:
    - "interphone0"
    - "interphone1"
  unlock_callers:
    - "interphone0"
  jpeg_query_s: "cd188d8e518cb12ad7a644f23928f64f"
  incoming_jpeg_max_files: 100
  answer_calls: false
  send_messages: true
  debug: false

schema:
  username: str
  password: password
  proxy: str
  register_uri: str
  message_uri: str
  entrance_uri: str
  allowed_caller: str?
  allowed_callers:
    - "str(1,)"
  unlock_callers:
    - "str(1,)"
  jpeg_query_s: "str(1,)"
  incoming_jpeg_max_files: "int(1,)"
  answer_calls: bool
  send_messages: bool
  debug: bool
