name: "AP Intercom Agent"
slug: ap_intercom_agent
description: "SIP agent for intercom control."
version: "0.1.0"
arch:
  - aarch64
url: "https://github.com/ikob/AP_intercom_agent"
startup: services
boot: auto
host_network: true
init: false

options:
  username: "cellphone0"
  password: null
  proxy: null
  register_uri: null
  message_uri: null
  entrance_uri: null
  allowed_caller: "interphone0"
  answer_calls: false
  send_messages: true

schema:
  username: str
  password: password
  proxy: str
  register_uri: str
  message_uri: str
  entrance_uri: str
  allowed_caller: str
  answer_calls: bool
  send_messages: bool
